name: Release
run-name: ${{ github.actor }} Building and pushing node_patched_npm
on: [push]

jobs:
  node_matrix:
    strategy:
      matrix:
        node_version: [18.20.2, 20.12.2]
        alpine_version: [3.18, 3.19]
        npm_version: [10.5.2]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-single-buildx
          restore-keys: |
            ${{ runner.os }}-single-buildx

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            NODE_VERSION=${{ matrix.node_version }}
            ALPINE_VERSION=${{ matrix.alpine_version }}
            NPM_VERSION=${{ matrix.npm_version }}
          tags: ghcr.io/tjsr/node_patched_npm:${{ matrix.node_version }}-alpine${{ matrix.alpine_version }}-npm${{ matrix.npm_version }}

      - name: Tag latest npm variants
        uses: docker/metadata-action@v5
        id: latest_image_npm
        with:
          context: workflow
          images: |
            ghcr.io/tjsr/node_patched_npm:${{ matrix.node_version }}-alpine${{ matrix.alpine_version }}-npm10.5.2
          tags: |
            type=raw,value=ghcr.io/tjsr/node_patched_npm:${{ matrix.node_version }}-alpine${{ matrix.alpine_version }}-npm-latest

      - name: Tag latest alpine variants
        uses: docker/metadata-action@v5
        id: latest_image_alpine
        with:
          context: workflow
          images: |
            ghcr.io/tjsr/node_patched_npm:${{ matrix.node_version }}-alpine3.19-npm${{ matrix.npm_version }}
          tags: |
            type=raw,value=ghcr.io/tjsr/node_patched_npm:${{ matrix.node_version }}-alpine-latest-npm${{ matrix.npm_version }}

      - name: Tag latest node variants
        uses: docker/metadata-action@v5
        id: latest_image_node
        with:
          context: workflow
          images: |
            ghcr.io/tjsr/node_patched_npm:20.12.2-alpine${{ matrix.alpine_version }}-npm${{ matrix.npm_version }}
          tags: |
            type=raw,value=ghcr.io/tjsr/node_patched_npm:latest-alpine${{ matrix.alpine_version }}-npm${{ matrix.npm_version }}

      - name: Push tag matrix of latest versions
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ steps.latest_image_npm.outputs.tags }} ,
            ${{ steps.latest_image_alpine.outputs.tags }} ,
            ${{ steps.latest_image_node.outputs.tags }}
