name: Release
run-name: ${{ github.actor }} Building and pushing node_patched_npm
on: [push]

jobs:
  node_matrix:
    strategy:
      matrix:
        node_version: ['18.20.3', '20.13.1', '20.14.0', '20.15.1']
        alpine_version: ['3.20']
        npm_version: ['10.7.0', '10.8.2']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-single-buildx
          restore-keys: |
            ${{ runner.os }}-single-buildx

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images for all variants and architectures.
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NODE_VERSION=${{ matrix.node_version }}
            ALPINE_VERSION=${{ matrix.alpine_version }}
            NPM_VERSION=${{ matrix.npm_version }}
          tags: ghcr.io/tjsr/node_patched_npm:${{ matrix.node_version }}-alpine${{ matrix.alpine_version }}-npm${{ matrix.npm_version }}

  latest:
    runs-on: ubuntu-latest
    needs: node_matrix
    steps:
      - name: Get branch names.
        id: branch-names
        uses: tj-actions/branch-names@v8

      - name: Running on any event.
        run: |
          echo "Default branch: ${{ steps.branch-names.outputs.default_branch }}"
        # Outputs: "Default branch: main"

      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-single-buildx
          restore-keys: |
            ${{ runner.os }}-single-buildx

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull, tag and push the latest image
        if: github.ref == 'refs/heads/main'
        env:
          NODE_VERSION: '20.15.1'
          ALPINE_VERSION: '3.20'
          NPM_VERSION: '10.8.2'
        run: |
          docker pull ghcr.io/tjsr/node_patched_npm:${NODE_VERSION}-alpine${ALPINE_VERSION}-npm${NPM_VERSION} || true
          docker tag ghcr.io/tjsr/node_patched_npm:${NODE_VERSION}-alpine${ALPINE_VERSION}-npm${NPM_VERSION} ghcr.io/tjsr/node_patched_npm:latest
          docker push ghcr.io/tjsr/node_patched_npm:latest

      - name: Pull, tag and push the latest image
        if: steps.branch-names.outputs.current_branch == 'develop/actions'
        id: meta
        uses: docker/metadata-action@v5
        env:
          NODE_VERSION: '20.15.1'
          ALPINE_VERSION: '3.20'
          NPM_VERSION: '10.8.2'
        with:
          images: ghcr.io/tjsr/node_patched_npm:${{ env.NODE_VERSION }}-alpine${{ env.ALPINE_VERSION }}-npm${{ env.NPM_VERSION }}
          tags: |
            type=raw,ghcr.io/tjsr/node_patched_npm:latest
            type=raw,ghcr.io/tjsr/node_patched_npm:latest-alpine${{ env.ALPINE_VERSION }}-npm${{ env.NPM_VERSION }}
            type=raw,ghcr.io/tjsr/node_patched_npm:latest-alpine-latest-npm${{ env.NPM_VERSION }}
            type=raw,ghcr.io/tjsr/node_patched_npm:latest-alpine-${{ env.ALPINE_VERSION }}-npm-latest
            type=raw,ghcr.io/tjsr/node_patched_npm:${{ env.NODE_VERSION }}-alpine-latest-npm${{ env.NPM_VERSION }}
            type=raw,ghcr.io/tjsr/node_patched_npm:${{ env.NODE_VERSION }}-alpine${{ env.ALPINE_VERSION }}-npm-latest
            type=raw,ghcr.io/tjsr/node_patched_npm:${{ env.NODE_VERSION }}-alpine-latest-npm-latest

      - name: Build and push tagged images
        uses: docker/build-push-action@v6
        with:
          cache-from: type=gha
          push: true
          tags: ${{ steps.meta.outputs.tags }}

