name: Release
run-name: ${{ github.actor }} Building and pushing node_patched_npm
on: [push, workflow_dispatch]
env:
  NODE_VERSION: '20.15.1'
  ALPINE_VERSION: '3.20'
  NPM_VERSION: '10.8.2'
  LATEST_TAG: '20.15.1-alpine3.20-npm10.8.2'
  LATEST_IMAGE_TAG: 'node_patched_npm:20.15.1-alpine3.20-npm10.8.2'
jobs:
  node_matrix:
    strategy:
      matrix:
        node_version: ['18.20.3', '20.15.1']
        alpine_version: ['3.20']
        npm_version: ['10.8.2']
    runs-on: ubuntu-latest
    steps:
      - id: matrix-image
        env:
          MATRIX_VERSION: "${{ matrix.node_version }}-alpine${{ matrix.alpine_version }}-npm${{ matrix.npm_version }}"
        run: |
          IS_LATEST=$([[ "$LATEST_TAG" == "$MATRIX_VERSION" ]] && echo true || echo false)
          echo "tag=$MATRIX_VERSION"
          echo "tag=$MATRIX_VERSION" >> "$GITHUB_OUTPUT"
          echo "isLatest=$IS_LATEST"
          echo "isLatest=$IS_LATEST" >> "$GITHUB_OUTPUT"
          echo "tarfile=/tmp/$MATRIX_VERSION.tar"
          echo "tarfile=/tmp/$MATRIX_VERSION.tar" >> "$GITHUB_OUTPUT"

      - uses: LIT-Protocol/artifact-exists-action@v0
        id: artifact-exists
        with:
          name: "node_patched_npm_${{ env.MATRIX_VERSION }}"

      - uses: actions/checkout@v4

      - name: Get branch names.
        id: branch-names
        uses: tj-actions/branch-names@v8

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Confirming that image will be pushed.
        id: push-image
        if: ${{ (github.ref == 'refs/heads/main' && steps.artifact-exists.outputs.exists == 'false') || github.event_name == 'workflow_dispatch' }}
        run: |
          echo "Pushing image."
          echo "Artifact already exists: ${{ steps.artifact-exists.outputs.exists }}"
          echo "Fired by workflow: ${{ github.event_name == 'workflow_dispatch' }}"
          echo "push=true" >> "$GITHUB_OUTPUT"

      - name: Latest tags meta
        id: image-meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/tjsr/node_patched_npm
          tags: |
            type=raw,value=${{ env.NODE_VERSION }}-alpine${{ env.ALPINE_VERSION }}-npm${{ env.NPM_VERSION }}
            type=raw,enable=${{ steps.matrix-image.outputs.isLatest == 'true' }},value=latest
            type=raw,enable=${{ steps.matrix-image.outputs.isLatest == 'true' }},value=alpine${{ env.ALPINE_VERSION }}-npm${{ env.NPM_VERSION }}
            type=raw,enable=${{ steps.matrix-image.outputs.isLatest == 'true' }},value=npm${{ env.NPM_VERSION }}
            type=raw,enable=${{ steps.matrix-image.outputs.isLatest == 'true' }},value=alpine-${{ env.ALPINE_VERSION }}
            type=raw,enable=${{ steps.matrix-image.outputs.isLatest == 'true' }},value=${{ env.NODE_VERSION }}-npm${{ env.NPM_VERSION }}
            type=raw,enable=${{ steps.matrix-image.outputs.isLatest == 'true' }},value=${{ env.NODE_VERSION }}-alpine${{ env.ALPINE_VERSION }}
            type=sha
            type=sha,format=long

      - name: Build and push all docker images.
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            NODE_VERSION=${{ matrix.node_version }}
            ALPINE_VERSION=${{ matrix.alpine_version }}
            NPM_VERSION=${{ matrix.npm_version }}
          tags: ${{ steps.image-meta.outputs.tags }}

      # - name: Upload OCI multi-platform image
      #   if: ${{ (github.ref == 'refs/heads/main' && steps.matrix-image.outputs.isLatest == 'true') || github.event_name == 'workflow_dispatch' }}
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: node_patched_npm_${{ steps.matrix-image.outputs.tag }}
      #     path: ${{ steps.matrix-image.outputs.tarfile }}

  latest:
    runs-on: ubuntu-latest
    if: true == false && (github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch')
    needs: node_matrix
    steps:
      - name: Get branch names.
        id: branch-names
        uses: tj-actions/branch-names@v8

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
            
      - name: Download OCI multi-platform artifact
        uses: actions/download-artifact@v4
        with:
          name: node_patched_npm_${{ env.LATEST_TAG }}
          path: /tmp/node_patched_npm

      - name: Debug - output the contents of the downloaded artifact
        run: ls -laR /tmp/node_patched_npm

      - name: Load tagged OCI multi-platform image.
        id: load-oci
        run: |
          docker import /tmp/node_patched_npm/${{ env.LATEST_TAG }}.tar ${{ env.LATEST_IMAGE_TAG }}

      - name: Tag the latest image with all the variants we want
        run: |
          BASECMD="docker tag ${{ env.LATEST_IMAGE_TAG }}"
          IMAGE="ghcr.io/tjsr/node_patched_npm"
          $BASECMD $IMAGE
          $BASECMD $IMAGE:latest
          $BASECMD $IMAGE:latest-alpine${{ env.ALPINE_VERSION }}-npm${{ env.NPM_VERSION }}
          $BASECMD $IMAGE:latest-alpine-latest-npm${{ env.NPM_VERSION }}
          $BASECMD $IMAGE:latest-npm${{ env.NPM_VERSION }}
          $BASECMD $IMAGE:latest-alpine-${{ env.ALPINE_VERSION }}-npm-latest
          $BASECMD $IMAGE:latest-alpine-${{ env.ALPINE_VERSION }}
          $BASECMD $IMAGE:${{ env.NODE_VERSION }}-alpine-latest-npm${{ env.NPM_VERSION }}
          $BASECMD $IMAGE:${{ env.NODE_VERSION }}-npm${{ env.NPM_VERSION }}-latest
          $BASECMD $IMAGE:${{ env.NODE_VERSION }}-npm${{ env.NPM_VERSION }}
          $BASECMD $IMAGE:${{ env.NODE_VERSION }}-alpine${{ env.ALPINE_VERSION }}-npm-latest
          $BASECMD $IMAGE:${{ env.NODE_VERSION }}-alpine${{ env.ALPINE_VERSION }}
          $BASECMD $IMAGE:${{ env.NODE_VERSION }}-alpine-latest-npm-latest
          $BASECMD $IMAGE:${{ env.NODE_VERSION }}-latest
          $BASECMD $IMAGE:${{ env.NODE_VERSION }}

      - name: Push tagged images
        run:
          docker push --all-tags ghcr.io/tjsr/node_patched_npm

